# mpv OSC configuration file by snad
# https://github.com/thisisshihan/mpv-player-config-snad

scaleforcedwindow=1
vidscale=yes
valign=0.65
seekbarstyle=knob
layout=floating
floatingwidth=500
floatingalpha=75
seekbarhandlesize=0.9
title=mpv.snad ~ ${!playlist-count==1:[${playlist-pos-1}/${playlist-count}] }${media-title}
title_mbtn_left_command=script-binding select/select-playlist; script-message-to osc osc-hide
title_mbtn_right_command=script-binding select/select-watch-history; script-message-to osc osc-hide
audio_track_mbtn_left_command=script-binding select/select-aid; script-message-to osc osc-hide
audio_track_mbtn_right_command=script-binding select/select-aid; script-message-to osc osc-hide
sub_track_mbtn_left_command=script-binding select/select-sid; script-message-to osc osc-hide
sub_track_mbtn_right_command=script-binding select/select-sid; script-message-to osc osc-hid
